name: go test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest","ubuntu-latest"]
        go: ["1.20.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}
      - run: "go test ./..."
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"
          install-go: false
          cache-key: ${{ matrix.go }}